### ISSUE TITLE
Gitter integration.

### ISSUE THREAD

**Issue by mikobuntu** [patrickballeux/screenstudio#1]
Hi Patrick, I have recently discovered that github has its own implementation of an #irc type chat client. I think this could be useful for brainstorming ideas and also as a quick help area for new users of ScreenStudio. See here for more details https://github.com/integrations/gitter 
Thanks 😆

**Comment by patrickballeux** [comment]
@mikobuntu , I did the integration, seems interesting.  

Thanks for the tip
